### ISSUE TITLE
Make the target repo configurable (point to knative/infra by default)

### ISSUE THREAD

**Issue by cardil** [knative/toolbox#6]
https://github.com/knative/toolbox/blob/292433b19b3627acfb6f52077c47e9dd796b378a/release-jobs-syncer/main.go#L34-L35

We need to adjust the above lines to point to the knative/infra by default. It would be good that this is configurable.

/kind bug

Related to https://github.com/knative/community/issues/1291

**Comment by krsna-m** [comment]
This tool should live where ever `configgen` lives since they are both infra specific. If they live in toolbox or in infra repo I don't care but for consistency sake they should live together.
